/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package computerlabsystem;

import java.awt.Color;

/**
 *
 * @author araos
 */
public class ForgotResetPassword extends javax.swing.JDialog {

    private String verificationCode;

    public String getVerificationCode() {
        return verificationCode;
    }

    public void setVerificationCode(String verificationCode) {
        this.verificationCode = verificationCode;
    }

    public ForgotResetPassword(java.awt.Frame parent, boolean modal, String verificationCode) {
        super(parent, modal);
        this.verificationCode = verificationCode;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkboxShowNewPass = new javax.swing.JCheckBox();
        checkboxShowReTypePassword = new javax.swing.JCheckBox();
        fieldNewPassword = new javax.swing.JPasswordField();
        fieldReTypePassword = new javax.swing.JPasswordField();
        btnSave = new javax.swing.JButton();
        lblWarningMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkboxShowNewPass.setBackground((new Color(0, 0, 0, 0)));
        checkboxShowNewPass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        checkboxShowNewPass.setBorderPainted(true);
        checkboxShowNewPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-hide-20.png"))); // NOI18N
        checkboxShowNewPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxShowNewPassActionPerformed(evt);
            }
        });
        getContentPane().add(checkboxShowNewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, 30));

        checkboxShowReTypePassword.setBackground((new Color(0, 0, 0, 0)));
        checkboxShowReTypePassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        checkboxShowReTypePassword.setBorderPainted(true);
        checkboxShowReTypePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-hide-20.png"))); // NOI18N
        checkboxShowReTypePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxShowReTypePasswordActionPerformed(evt);
            }
        });
        getContentPane().add(checkboxShowReTypePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, 30));

        fieldNewPassword.setText("jPasswordField1");
        getContentPane().add(fieldNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 63, 191, -1));

        fieldReTypePassword.setText("jPasswordField2");
        getContentPane().add(fieldReTypePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 155, 190, -1));

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 230, 40));

        lblWarningMessage.setText("jLabel1");
        getContentPane().add(lblWarningMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkboxShowReTypePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxShowReTypePasswordActionPerformed
        if (checkboxShowReTypePassword.isSelected()) {
            checkboxShowReTypePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-eye-20.png")));
            fieldReTypePassword.setEchoChar((char) 0);

        } else {
            checkboxShowReTypePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-hide-20.png")));
            fieldReTypePassword.setEchoChar('*');
        }
    }//GEN-LAST:event_checkboxShowReTypePasswordActionPerformed

    private void checkboxShowNewPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxShowNewPassActionPerformed
        if (checkboxShowNewPass.isSelected()) {
            checkboxShowNewPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-eye-20.png")));
            fieldNewPassword.setEchoChar((char) 0);

        } else {
            checkboxShowNewPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-hide-20.png")));
            fieldNewPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_checkboxShowNewPassActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        newPassword = String.valueOf(fieldNewPassword.getPassword());
        retypePassword = String.valueOf(fieldReTypePassword.getPassword());
        if (newPassword.isEmpty() && retypePassword.isEmpty()) {
            lblWarningMessage.setText("Please Enter your new password and re-type before Hitting the Save Button");
        } else if (newPassword.isEmpty()) {

        } else if (retypePassword.isEmpty()) {

        } else if (newPassword.length() < 8) {
            lblWarningMessage.setText("Password should be at least 8 characters long.");
        } else {
            String hashedPassword = ComLabMethods.hashPassword(newPassword);
            ForgetPasswordMethods.updatePassword(hashedPassword, verificationCode);
            dispose();
        }

    }//GEN-LAST:event_btnSaveActionPerformed
    String newPassword, retypePassword;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox checkboxShowNewPass;
    private javax.swing.JCheckBox checkboxShowReTypePassword;
    private javax.swing.JPasswordField fieldNewPassword;
    private javax.swing.JPasswordField fieldReTypePassword;
    private javax.swing.JLabel lblWarningMessage;
    // End of variables declaration//GEN-END:variables
}
