/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package computerlabsystem;

/**
 *
 * @author araos
 */
public class ForgetPasswordVerification extends javax.swing.JDialog {

    private String email;

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public ForgetPasswordVerification(java.awt.Frame parent, boolean modal, String email) {
        super(parent, modal);
        this.email = email;
        initComponents();
        lblWarningMessage.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOTPverification = new javax.swing.JLabel();
        btnConfirmCode = new javax.swing.JButton();
        btnBackToLogin = new javax.swing.JButton();
        txtCode = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaMessage = new javax.swing.JTextArea();
        lblWarningMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOTPverification.setFont(new java.awt.Font("Segoe UI Semibold", 1, 30)); // NOI18N
        lblOTPverification.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOTPverification.setText("OTP VERIFICATION");
        getContentPane().add(lblOTPverification, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 320, -1));

        btnConfirmCode.setText("jButton1");
        btnConfirmCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmCodeActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 258, -1));

        btnBackToLogin.setText("jButton2");
        btnBackToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnBackToLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 128, -1));

        txtCode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCode.setText("jTextField1");
        txtCode.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        txtCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeActionPerformed(evt);
            }
        });
        getContentPane().add(txtCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 310, 40));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jScrollPane1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jScrollPane1.setWheelScrollingEnabled(false);

        textAreaMessage.setEditable(false);
        textAreaMessage.setBackground(new java.awt.Color(255, 51, 0));
        textAreaMessage.setColumns(20);
        textAreaMessage.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        textAreaMessage.setRows(5);
        textAreaMessage.setText("\nWe've sent a One-Time Password (OTP)  \nto your registered email for verification. ");
        jScrollPane1.setViewportView(textAreaMessage);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 290, 100));

        lblWarningMessage.setText("jLabel1");
        getContentPane().add(lblWarningMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeActionPerformed

    }//GEN-LAST:event_txtCodeActionPerformed

    private void btnBackToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToLoginActionPerformed
        dispose();
    }//GEN-LAST:event_btnBackToLoginActionPerformed

    private void btnConfirmCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmCodeActionPerformed
        ComLabMethods clm = new ComLabMethods();
        String verificationCode = clm.getUpdatedCode(email);
        String inputCode = txtCode.getText();
        if (inputCode.isEmpty()) {
            lblWarningMessage.setText("Please Enter the code before you hit the reset Password");
        } else if (inputCode.equals(verificationCode)) {
            ForgotResetPassword dialog = new ForgotResetPassword(new javax.swing.JFrame(), true, verificationCode);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dispose();
            dialog.setVisible(true);
        }
        
    }//GEN-LAST:event_btnConfirmCodeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToLogin;
    private javax.swing.JButton btnConfirmCode;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblOTPverification;
    private javax.swing.JLabel lblWarningMessage;
    private javax.swing.JTextArea textAreaMessage;
    private javax.swing.JTextField txtCode;
    // End of variables declaration//GEN-END:variables
}
