/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package computerlabsystem;

import java.awt.Color;

/**
 *
 * @author araos
 */
public class ForgotResetPassword extends javax.swing.JDialog {

    private String verificationCode;

    public String getVerificationCode() {
        return verificationCode;
    }

    public void setVerificationCode(String verificationCode) {
        this.verificationCode = verificationCode;
    }

    public ForgotResetPassword(java.awt.Frame parent, boolean modal, String verificationCode) {
        super(parent, modal);
        this.verificationCode = verificationCode;
        initComponents();
        lblWarningMessage.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradient1 = new computerlabsystem.Design.PanelGradient();
        checkboxShowNewPass = new javax.swing.JCheckBox();
        checkboxShowReTypePassword = new javax.swing.JCheckBox();
        fieldNewPassword = new javax.swing.JPasswordField();
        fieldReTypePassword = new javax.swing.JPasswordField();
        btnSave = new javax.swing.JButton();
        lblWarningMessage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGradient1.setColorPrimary(new java.awt.Color(109, 113, 249));

        checkboxShowNewPass.setBackground((new Color(0, 0, 0, 0)));
        checkboxShowNewPass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        checkboxShowNewPass.setBorderPainted(true);
        checkboxShowNewPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-hide-20.png"))); // NOI18N
        checkboxShowNewPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxShowNewPassActionPerformed(evt);
            }
        });
        panelGradient1.add(checkboxShowNewPass);
        checkboxShowNewPass.setBounds(290, 160, 30, 40);

        checkboxShowReTypePassword.setBackground((new Color(0, 0, 0, 0)));
        checkboxShowReTypePassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        checkboxShowReTypePassword.setBorderPainted(true);
        checkboxShowReTypePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-hide-20.png"))); // NOI18N
        checkboxShowReTypePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxShowReTypePasswordActionPerformed(evt);
            }
        });
        panelGradient1.add(checkboxShowReTypePassword);
        checkboxShowReTypePassword.setBounds(290, 240, 30, 40);
        panelGradient1.add(fieldNewPassword);
        fieldNewPassword.setBounds(80, 160, 240, 40);
        panelGradient1.add(fieldReTypePassword);
        fieldReTypePassword.setBounds(80, 240, 240, 40);

        btnSave.setBackground(new java.awt.Color(0, 0, 51));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("SAVE");
        btnSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        panelGradient1.add(btnSave);
        btnSave.setBounds(110, 300, 190, 30);

        lblWarningMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWarningMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-error-24.png"))); // NOI18N
        lblWarningMessage.setText("jLabel1");
        panelGradient1.add(lblWarningMessage);
        lblWarningMessage.setBounds(50, 360, 290, 20);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SET PASSWORD");
        panelGradient1.add(jLabel1);
        jLabel1.setBounds(90, 20, 220, 16);

        jLabel2.setText("Create New Password");
        panelGradient1.add(jLabel2);
        jLabel2.setBounds(90, 100, 240, 16);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-check-lock-30.png"))); // NOI18N
        panelGradient1.add(jLabel3);
        jLabel3.setBounds(30, 240, 50, 40);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-password-30.png"))); // NOI18N
        panelGradient1.add(jLabel4);
        jLabel4.setBounds(30, 156, 50, 40);

        getContentPane().add(panelGradient1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void checkboxShowReTypePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxShowReTypePasswordActionPerformed
        if (checkboxShowReTypePassword.isSelected()) {
            checkboxShowReTypePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-eye-20.png")));
            fieldReTypePassword.setEchoChar((char) 0);

        } else {
            checkboxShowReTypePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-hide-20.png")));
            fieldReTypePassword.setEchoChar('*');
        }
    }//GEN-LAST:event_checkboxShowReTypePasswordActionPerformed

    private void checkboxShowNewPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxShowNewPassActionPerformed
        if (checkboxShowNewPass.isSelected()) {
            checkboxShowNewPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-eye-20.png")));
            fieldNewPassword.setEchoChar((char) 0);

        } else {
            checkboxShowNewPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-hide-20.png")));
            fieldNewPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_checkboxShowNewPassActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        newPassword = String.valueOf(fieldNewPassword.getPassword());
        retypePassword = String.valueOf(fieldReTypePassword.getPassword());
        
        lblWarningMessage.setVisible(true);
        if (newPassword.isEmpty() && retypePassword.isEmpty()) {
            lblWarningMessage.setText("Please Enter your new password and re-type before Hitting the Save Button");
        } else if (newPassword.isEmpty()) {

        } else if (retypePassword.isEmpty()) {

        } else if (newPassword.length() < 8) {
            lblWarningMessage.setText("Password should be at least 8 characters long.");
        } else {
            String hashedPassword = ComLabMethods.hashPassword(newPassword);
            ForgetPasswordMethods.updatePassword(hashedPassword, verificationCode);
            dispose();
        }

    }//GEN-LAST:event_btnSaveActionPerformed
    String newPassword, retypePassword;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox checkboxShowNewPass;
    private javax.swing.JCheckBox checkboxShowReTypePassword;
    private javax.swing.JPasswordField fieldNewPassword;
    private javax.swing.JPasswordField fieldReTypePassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblWarningMessage;
    private computerlabsystem.Design.PanelGradient panelGradient1;
    // End of variables declaration//GEN-END:variables
}
