/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package computerlabsystem;

import java.awt.Component;
import java.awt.event.ActionListener;
import javax.swing.SwingUtilities;

/**
 *
 * @author araos
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
        initComponents();
        lblWarningMsg.setVisible(false);
    }

    public void addEventRegister(ActionListener event) {
        btnGoToSignUp.addActionListener(event);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbStudentFacultyID = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        fieldPass = new javax.swing.JPasswordField();
        txtStudentFacultyID = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        btnGoToSignUp = new javax.swing.JButton();
        lblWarningMsg = new javax.swing.JLabel();
        chckbxShowPass = new javax.swing.JCheckBox();
        lblAttemptsLeft = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbStudentFacultyID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbStudentFacultyID.setText("Student/Faculty ID");
        add(lbStudentFacultyID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 121, -1, -1));

        lblPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPass.setText("Password");
        add(lblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 174, -1, -1));

        fieldPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(fieldPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 171, 150, -1));

        txtStudentFacultyID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtStudentFacultyID.setText("ID");
        add(txtStudentFacultyID, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 118, 150, -1));

        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 267, -1, -1));

        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 267, -1, -1));

        btnGoToSignUp.setText("GO TO SIGN UP");
        add(btnGoToSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 325, -1, -1));

        lblWarningMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWarningMsg.setIcon(new javax.swing.ImageIcon("C:\\Users\\araos\\Downloads\\icons8-error-24.png")); // NOI18N
        lblWarningMsg.setText("jLabel3");
        add(lblWarningMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 366, 235, -1));

        chckbxShowPass.setText("show");
        chckbxShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckbxShowPassActionPerformed(evt);
            }
        });
        add(chckbxShowPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 172, -1, -1));

        lblAttemptsLeft.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAttemptsLeft.setText("jLabel1");
        add(lblAttemptsLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 408, 92, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void chckbxShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckbxShowPassActionPerformed
        if (chckbxShowPass.isSelected()) {
            fieldPass.setEchoChar((char) 0);
        } else {
            fieldPass.setEchoChar('*');
        }
    }//GEN-LAST:event_chckbxShowPassActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        stuFaculID = txtStudentFacultyID.getText();
        pass = String.valueOf(fieldPass.getPassword());

        lblWarningMsg.setVisible(true);
        if (stuFaculID.isEmpty() && pass.isEmpty()) {
            lblWarningMsg.setText("Please input in the space provided");
        } else if (stuFaculID.isEmpty()) {
            lblWarningMsg.setText("Please input your email");
        } else if (pass.isEmpty()) {
            lblWarningMsg.setText("Please input your password");
        } else {
            String userDetails = ComLabMethods.getUserDetails(stuFaculID, pass);
            if (!userDetails.equals("false")) {
                String[] parts = userDetails.split(",");
                String userRole = parts[0];
                String sfID = parts[1];
                String fname = parts[2];
                String lname = parts[3];
                
                String fullName = fname + " " + lname;
                //  String hashedPassword = ComLabMethods.hashPassword(pass);
                if (userRole.equals("ADMIN")) {
                    AdminDashboard admn = new AdminDashboard(fname, sfID);
                    admn.setVisible(true);
                    SwingUtilities.getWindowAncestor((Component) evt.getSource()).dispose();
                } else if (userRole.equals("STUDENT") || userRole.equals("FACULTY")) {
                    ComLabMethods.logUserLogin(sfID, fullName, pass);
                    System.out.println("anooonnaaaaa");
                     SwingUtilities.getWindowAncestor((Component) evt.getSource()).dispose();
                }
            } else {
                attempt--;
                lblWarningMsg.setText("Invalid Credentials");
                lblAttemptsLeft.setText(String.valueOf(attempt));
                if (attempt <= 0) {
                    InvalidInput dialog = new InvalidInput(new javax.swing.JFrame(), true);
                    dialog.setVisible(true); // Show the dialog
                    attempt = 3;
                }

            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtStudentFacultyID.setText("");
        fieldPass.setText("");
        lblWarningMsg.setVisible(false);
    }//GEN-LAST:event_btnClearActionPerformed

    private static int attempt = 3;
    private String stuFaculID, pass;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnGoToSignUp;
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox chckbxShowPass;
    private javax.swing.JPasswordField fieldPass;
    private javax.swing.JLabel lbStudentFacultyID;
    private javax.swing.JLabel lblAttemptsLeft;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblWarningMsg;
    private javax.swing.JTextField txtStudentFacultyID;
    // End of variables declaration//GEN-END:variables
}
