/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package computerlabsystem;

import java.awt.event.ActionListener;

/**
 *
 * @author araos
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
        initComponents();
        lblWarningMsg.setVisible(false);
    }

    public void addEventRegister(ActionListener event) {
        btnGoToSignUp.addActionListener(event);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbStudentFacultyID = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        fieldPass = new javax.swing.JPasswordField();
        txtStudentFacultyID = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        btnGoToSignUp = new javax.swing.JButton();
        lblWarningMsg = new javax.swing.JLabel();
        chckbxShowPass = new javax.swing.JCheckBox();
        lblAttemptsLeft = new javax.swing.JLabel();

        lbStudentFacultyID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbStudentFacultyID.setText("Student/Faculty ID");

        lblPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPass.setText("Password");

        fieldPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtStudentFacultyID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtStudentFacultyID.setText("ID");

        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnGoToSignUp.setText("GO TO SIGN UP");

        lblWarningMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWarningMsg.setIcon(new javax.swing.ImageIcon("C:\\Users\\araos\\Downloads\\icons8-box-important-20.png")); // NOI18N
        lblWarningMsg.setText("jLabel3");

        chckbxShowPass.setText("show");
        chckbxShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckbxShowPassActionPerformed(evt);
            }
        });

        lblAttemptsLeft.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAttemptsLeft.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnClear)
                        .addGap(55, 55, 55)
                        .addComponent(btnLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(lblAttemptsLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(lblWarningMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(btnGoToSignUp)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lbStudentFacultyID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtStudentFacultyID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(lblPass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(fieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chckbxShowPass)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbStudentFacultyID)
                    .addComponent(txtStudentFacultyID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPass)
                    .addComponent(fieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chckbxShowPass))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnClear))
                .addGap(35, 35, 35)
                .addComponent(btnGoToSignUp)
                .addGap(18, 18, 18)
                .addComponent(lblWarningMsg)
                .addGap(18, 18, 18)
                .addComponent(lblAttemptsLeft)
                .addContainerGap(56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chckbxShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckbxShowPassActionPerformed
        if (chckbxShowPass.isSelected()) {
            fieldPass.setEchoChar((char) 0);
        } else {
            fieldPass.setEchoChar('*');
        }
    }//GEN-LAST:event_chckbxShowPassActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        stuFaculID = txtStudentFacultyID.getText();
        pass = String.valueOf(fieldPass.getPassword());

        lblWarningMsg.setVisible(true);
        if (stuFaculID.isEmpty() && pass.isEmpty()) {
            lblWarningMsg.setText("Please input in the space provided");
        } else if (stuFaculID.isEmpty()) {
            lblWarningMsg.setText("Please input your email");
        } else if (pass.isEmpty()) {
            lblWarningMsg.setText("Please input your password");
        } else {
            String userDetails = ComLabMethods.getUserDetails(stuFaculID, pass);
            if (!userDetails.equals("false")) {
                String[] parts = userDetails.split(",");
                String sfID = parts[0];
                String fname = parts[1];
                String lname = parts[2];
                String userRole = parts[3];
                String fullName = fname + " " + lname;
              //  String hashedPassword = ComLabMethods.hashPassword(pass);
                if (userRole.equals("ADMIN")) {
                    AdminDashboard admn = new AdminDashboard(fname);
                    admn.setVisible(true);
                } else if (userRole.equals("STUDENT") || userRole.equals("FACULTY")) {
                    ComLabMethods.logUserLogin(sfID, fullName, pass);
                    System.out.println("anooonnaaaaa");
                }
            } else {
                attempt--;
                lblWarningMsg.setText("Invalid Credentials");
                lblAttemptsLeft.setText(String.valueOf(attempt));
                if (attempt <= 0) {
                    InvalidInput dialog = new InvalidInput(new javax.swing.JFrame(), true);
                    dialog.setVisible(true); // Show the dialog
                    attempt = 3;
                }

            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtStudentFacultyID.setText("");
        fieldPass.setText("");
        lblWarningMsg.setVisible(false);
    }//GEN-LAST:event_btnClearActionPerformed

    private static int attempt = 3;
    private String stuFaculID, pass;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnGoToSignUp;
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox chckbxShowPass;
    private javax.swing.JPasswordField fieldPass;
    private javax.swing.JLabel lbStudentFacultyID;
    private javax.swing.JLabel lblAttemptsLeft;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblWarningMsg;
    private javax.swing.JTextField txtStudentFacultyID;
    // End of variables declaration//GEN-END:variables
}
